How to properly name the git branch
dointeractive/guides pull request #1
Opened 2018-02-13 14:33 UTC by volhit

one more contributing rule

2018-02-13 14:40 UTC, mrsutter commented on contributing/README.md
> +report-fix-ABC-123
давай сделаем осмысленные примеры а не super-feature и report-fix

2018-02-13 14:40 UTC, mrsutter commented on contributing/README.md
> +2. If you know the number of Jira task, use it as part of the branch name. It allows Jira to auto-add these branches and pull requests with them to the
вычитывай плс что пишешь. the - 2 раза подряд

2018-02-13 15:12 UTC, volhit commented on contributing/README.md
> +report-fix-ABC-123
fixed

2018-02-13 15:12 UTC, volhit commented on contributing/README.md
> +2. If you know the number of Jira task, use it as part of the branch name. It allows Jira to auto-add these branches and pull requests with them to the
fixed

2018-03-19 09:19 UTC, oleglitvin requested changes
1. Task number should go before branch name
2. Capital letters are not allowed at branch names

2018-03-19 09:28 UTC, volhit commented
@oleglitvin 
fixed

2018-03-19 09:40 UTC, oleglitvin approved these changes

2018-03-19 09:40 UTC, merged